### ISSUE TITLE
Text input on search bar

### ISSUE THREAD

**Issue by gpessia** [karelvuong/st-primer#11]
perhaps it would be better to align all the center...
![schermata 2015-03-25 alle 12 34 41](https://cloud.githubusercontent.com/assets/68612/6823786/c9e6f924-d2eb-11e4-9fd7-df64022ada0c.png)

**Comment by ghost** [comment]
This doesn't seem to be possible with Sublime Text. Spacegray, the theme that this is based off of, centers the text and input field by adding a `content_margin: [8, 8]` which decreases the height of the input but vertically centers it.

**Comment by gpessia** [comment]
try to see [Predown](https://github.com/jamiewilson/predawn/blob/master/predawn.sublime-theme#L640) 
![](https://github.com/jamiewilson/predawn/raw/master/screenshots/find-replace.png) or [amCoder](https://github.com/auiWorks/amCoder/blob/master/amCoder.sublime-theme)

**Comment by ghost** [comment]
Thanks for the link @gpessia, I think I got it. :smiley:

**Comment by ghost** [comment]
This has been fixed and will be pushed in the next release.

**Comment by wpp** [comment]
Hi!

Thanks a lot for the theme. Great work!

Looks like I still have an issue with the input height:
![screen shot 2016-11-24 at 17 11 39](https://cloud.githubusercontent.com/assets/942021/20604979/646278e4-b269-11e6-8c6b-24728d13a225.png)
